version: '2'
#
services:
  iris:
    build:
      context: .
      args:
        COMMIT_ID: ${COMMIT_ID}
    image: containers.intersystems.com/intersystems/iris-community:2022.1.0.209.0
    hostname: iris

    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"

    command:
      --check-caps false

    volumes:
    - ./:/ISC

    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge.cpf

    mem_limit: 1G

  dotnet:
    build:
      context: dotnet50
      dockerfile: Dockerfile
    command: bash
    restart: always
    tty: true
    environment:
      - TZ=JST-9      
    volumes:
      - ./:/source
      
    mem_limit: 1G
